nginx:
 build: ./nginx
 ports:
    - "80:80"
 links:
   - node1:node1
   - node2:node2
   - node3:node3

redis:
  image: redis
  ports:
    - "6379"

node1:
  build: ./node
  links:
    - redis
  ports:
    - "8080"

node2:
  build: ./node
  links:
    - redis
  ports:
    - "8080"

node3:
  build: ./node
  links:
    - redis
  ports:
    - "8080"
